apiVersion: apps/v1
kind: Deployment
metadata:
  name: jork-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jork-api
  template:
    metadata:
      labels:
        app: jork-api
    spec:
      containers:
        - name: jork-api-container
          image: marcusradell/jork-api:latest
          ports:
            - containerPort: 3000
