apiVersion: apps/v1
kind: Deployment
metadata:
  name: jork-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jork-api
  template:
    metadata:
      labels:
        app: jork-api
    spec:
      containers:
        - name: jork-api-container
          image: marcusradell/jork-api:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: jork-api
spec:
  type: NodePort
  selector:
    app: jork-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
